env:
  es6: true
  browser: true
  commonjs: true
  jest: true
  node: true

parser: "@typescript-eslint/parser"
extends: ["plugin:react/recommended"]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 9
  sourceType: module
  project: "./tsconfig.json"

plugins: ["react"]

settings:
  react:
    version: "16"

rules:
  quotes: ["error", "double"]
